### ISSUE TITLE
گزارش مشکل 

### ISSUE THREAD

**Issue by ArinHcp** [saeedalipoor/RTLPLZ#1]
اقای علی پور سلام. مرسی بابت  پلاگین خوبی که توسعه دادی برای فیگما. در آخرین آپدیت هایی که منتشر کردی  شورت کات های Wrap و Reverse غیرفعال شدند و منتقل شده به منوی داخل پلاگین ها. اما من بعد از چند بار تست موفق نشدم تایپ های فارسی رو اصلاح کنم. به نظرم حالت قبل خیلی بهتر و سریعتر کار می کرد. سریعتر چون مجبوریم برای هر کلمه و عبارت بارها و بارها یک فراند زمان گیر رو تکرار کنیم که البته گویا مشکلاتی داره که ممنون میشم بررسی کنید.

ممنون.

**Comment by saeedalipoor** [comment]
سلام وقت بخیر
ببینید مشکلی که میونبرهای قبلی داشت این بود که حتماً باید پنجرهٔ پلاگین باز می‌بود، و از این آپدیت به بعد دیگه نیاز نیست برای متن‌های کوتاه یا کپی شده پنجره رو باز کنید.
کافیه متن رو بنویسید و مستقیماً‌اون کامند پلاگین رو اجرا کنید
برای اجرا کردنش هم می‌تونید از طریق رفتن به منو این کار رو بکنید و هم اینکه از میونبر فیگما برای پیدا کردن منو استفاده کنید.
ctrl+/
سعیم رو می‌کنم تو آپدیت بعدی دکمه‌ها رو مجدد توی UI بذارم
