### ISSUE TITLE
 doesn't work on chromium

### ISSUE THREAD

**Issue by Gictorbit** [saeedalipoor/RTLPLZ#2]
I use Figma web edition on chromium with Linux, so for RTL support I installed your plugin and I tested Farsi seems it doesn't work.
doesn't show any Farsi letter

![image](https://user-images.githubusercontent.com/34630603/86520190-ec59e280-be56-11ea-988b-bb57e24d3152.png)

also, I used `rtl plz` editor and nothing happen, any idea?

**Comment by saeedalipoor** [comment]
You should set a font that has arabic or persian glyphs. Try Arial, tahoma etc.
