### ISSUE TITLE
العنوان 1

### ISSUE THREAD

**Issue by GuuuWei** [saeedalipoor/RTLPLZ#5]
miss charter when string has numbers

reverse to "1 ﻥﺍﻮﻨﻌﻟﺍ"

![image](https://user-images.githubusercontent.com/11283300/134662259-2ff436c9-1848-4054-be1d-2f746d1dcfd2.png)

**Comment by saeedalipoor** [comment]
There are glyphs missing in the font, please contact the font provider.
You can enter an Arabic character after a number or ltr character to keep the general form of characters and prevent the plugin from reshaping them.
https://en.wikipedia.org/wiki/Arabic_script_in_Unicode
