### ISSUE TITLE
Miss charter when string has numbers *again*

### ISSUE THREAD

**Issue by txtwork** [saeedalipoor/RTLPLZ#7]
miss charter when string has numbers *again*

Please check the image, I am sure it's not a typeface problem.

اﻟﻌﻨﻮان 1

![image](https://user-images.githubusercontent.com/11283300/135232108-1c37b391-52e3-43f9-9835-0ee7f55ae288.png)

Plugin “Arabic & RTL Support “
https://www.figma.com/community/plugin/732290356467065314/Arabic-%26-RTL-Support

**Comment by saeedalipoor** [comment]
This file shows that the font is missing isolated glyphs.
https://www.figma.com/file/UMNiTxDKu2gdDmSMci7A2y
Thanks, I'll publish an update on this case.

**Comment by MT-AQAI** [comment]
سلام 
ممنون بابت ساخت این پلاگین ارزشمند
اما
تروخدا انقدر آپدیت های الکی نده فقط داری کار خراب میکنی 
ما یه پروژه خیلی عظیمی داخل فیگما داریم دیزاین میکنیم که آپدیت های شما داره تکست پروژه ما رو به خطر می‌اندازه
نکن عزیز آروم بشین
یه پلاگین ساده که انقدر اپدیت نمی کنند
