### ISSUE TITLE
گزارش یک باگ

### ISSUE THREAD

**Issue by adamjfarzam** [saeedalipoor/RTLPLZ#8]
سلام
وقت به خیر

برای من بعضی وقت‌ها که تو پلاگین فارسی و انگلیسی رو با هم می نویسم، حروف فارسی تو اون خط رو به صورت جدا جدا و غیرمتصل می کنه
مثل عکس پیوست شده
![Test text](https://user-images.githubusercontent.com/92952246/142010385-b6c683a7-4bb6-4028-8f48-b5385a285ba7.jpg)
ممنون

**Comment by saeedalipoor** [comment]
سلام
توی آپدیت بعدی این مشکل برطرف خواهد‌شد.

ممنون از مشارکتت
