### ISSUE TITLE
Noto Sans Arabic Issue

### ISSUE THREAD

**Issue by hn382** [saeedalipoor/RTLPLZ#9]
When I use Noto Sans Arabic font, the Arabic characters shown in the attached appears incorrectly.

![noto-sans-arabic-issue](https://user-images.githubusercontent.com/96095094/145920040-73ff0d12-47cf-427b-b774-5ff414a78c05.jpg)

**Comment by saeedalipoor** [comment]
That's because Figma's issue in positioning diarictic. I reported it to Figma. I hope they fix it soon.
